-- CREATE CUSTOM USER ROLE ENUM
CREATE TYPE user_role AS ENUM ('super_admin', 'admin', 'editor');

-- CREATE PROFILES TABLE (linked to auth.users)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  email TEXT NOT NULL,
  full_name TEXT,
  avatar_url TEXT,
  role user_role DEFAULT 'editor'::user_role NOT NULL
);

-- ENABLE ROW LEVEL SECURITY FOR PROFILES
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- TRIGGER TO AUTOMATICALLY CREATE PROFILE ON SIGNUP
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'full_name', ''),
    -- First user is super_admin, subsequent are editor by default
    CASE 
      WHEN NOT EXISTS (SELECT 1 FROM public.profiles) THEN 'super_admin'::user_role
      ELSE 'editor'::user_role
    END
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- HELPER FUNCTIONS FOR RLS POLICIES
CREATE OR REPLACE FUNCTION get_user_role()
RETURNS user_role AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid();
$$ LANGUAGE sql SECURITY DEFINER;

-- 1. SERVICES TABLE
CREATE TABLE services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  icon TEXT, -- Lucide icon name
  image_url TEXT,
  tag TEXT,
  duration TEXT,
  value TEXT,
  scope TEXT,
  status TEXT DEFAULT 'published' NOT NULL, -- draft, published, archived
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. PROJECT CATEGORIES
CREATE TABLE project_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL
);

-- 3. PROJECTS TABLE
CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  category_id BIGINT REFERENCES project_categories(id) ON DELETE SET NULL,
  location TEXT,
  year TEXT,
  value TEXT,
  image_url TEXT,
  description TEXT,
  status TEXT DEFAULT 'published' NOT NULL, -- draft, published, archived
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TEAM MEMBERS
CREATE TABLE team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  title TEXT NOT NULL,
  image_url TEXT,
  projects_completed INTEGER DEFAULT 0,
  years_experience INTEGER DEFAULT 0,
  linkedin_url TEXT,
  twitter_url TEXT,
  email TEXT,
  display_order INTEGER DEFAULT 0,
  status TEXT DEFAULT 'published' NOT NULL, -- draft, published, archived
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. TESTIMONIALS
CREATE TABLE testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT,
  company TEXT,
  text TEXT NOT NULL,
  rating INTEGER DEFAULT 5,
  avatar_url TEXT,
  status TEXT DEFAULT 'published' NOT NULL, -- draft, published, archived
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. BLOG CATEGORIES
CREATE TABLE blog_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL
);

-- 7. BLOG POSTS
CREATE TABLE blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  content TEXT,
  excerpt TEXT,
  image_url TEXT,
  category_id BIGINT REFERENCES blog_categories(id) ON DELETE SET NULL,
  author_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'draft' NOT NULL, -- draft, published, archived
  published_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. CAREERS
CREATE TABLE careers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  department TEXT,
  location TEXT,
  type TEXT, -- Full-time, Part-time, Contract
  description TEXT,
  requirements TEXT[],
  benefits TEXT[],
  status TEXT DEFAULT 'published' NOT NULL, -- draft, published, archived
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. EQUIPMENT
CREATE TABLE equipment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT,
  image_url TEXT,
  last_maintenance TIMESTAMP WITH TIME ZONE,
  status TEXT DEFAULT 'available' NOT NULL, -- available, maintenance, in-use, archived
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. MEDIA LIBRARY (Metadata tracker for uploaded assets)
CREATE TABLE media_library (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name TEXT NOT NULL,
  file_url TEXT NOT NULL,
  file_type TEXT,
  file_size INTEGER,
  uploaded_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 11. CONTACT MESSAGES
CREATE TABLE contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  subject TEXT,
  message TEXT NOT NULL,
  read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 12. QUOTE REQUESTS
CREATE TABLE quote_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_type TEXT,
  budget TEXT,
  email TEXT NOT NULL,
  project_description TEXT,
  status TEXT DEFAULT 'pending', -- pending, reviewed, contact_made
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 13. WEBSITE SETTINGS
CREATE TABLE website_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 14. SEO METADATA
CREATE TABLE seo_metadata (
  page_path TEXT PRIMARY KEY, -- e.g. '/', '/services', '/contact'
  title TEXT NOT NULL,
  meta_description TEXT,
  keywords TEXT[],
  og_image TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 15. FAQS TABLE
CREATE TABLE faqs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  display_order INTEGER DEFAULT 0,
  status TEXT DEFAULT 'published' NOT NULL, -- draft, published, archived
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- ─────────────────────────────────────────────────────────────────────────────
-- ENABLE ROW LEVEL SECURITY ON ALL TABLES
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE careers ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE media_library ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE website_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE seo_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE faqs ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- RLS POLICIES
-- ─────────────────────────────────────────────────────────────────────────────

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Super Admins can manage all profiles" ON profiles FOR ALL USING (get_user_role() = 'super_admin'::user_role);

-- General Content Read Policies (Allow Public Select)
CREATE POLICY "Allow public read services" ON services FOR SELECT USING (status = 'published');
CREATE POLICY "Allow public read project_categories" ON project_categories FOR SELECT USING (true);
CREATE POLICY "Allow public read projects" ON projects FOR SELECT USING (status = 'published');
CREATE POLICY "Allow public read team_members" ON team_members FOR SELECT USING (status = 'published');
CREATE POLICY "Allow public read testimonials" ON testimonials FOR SELECT USING (status = 'published');
CREATE POLICY "Allow public read blog_categories" ON blog_categories FOR SELECT USING (true);
CREATE POLICY "Allow public read blog_posts" ON blog_posts FOR SELECT USING (status = 'published' OR get_user_role() IS NOT NULL);
CREATE POLICY "Allow public read careers" ON careers FOR SELECT USING (status = 'published' OR get_user_role() IS NOT NULL);
CREATE POLICY "Allow public read equipment" ON equipment FOR SELECT USING (status != 'archived');
CREATE POLICY "Allow public read website_settings" ON website_settings FOR SELECT USING (true);
CREATE POLICY "Allow public read seo_metadata" ON seo_metadata FOR SELECT USING (true);
CREATE POLICY "Allow public read faqs" ON faqs FOR SELECT USING (status = 'published');

-- Editor/Admin/Super Admin Write Policies
CREATE POLICY "Editors/Admins/SuperAdmins can write services" ON services FOR ALL 
  USING (get_user_role() IN ('editor', 'admin', 'super_admin'))
  WITH CHECK (get_user_role() IN ('editor', 'admin', 'super_admin'));

CREATE POLICY "Editors/Admins/SuperAdmins can write project_categories" ON project_categories FOR ALL 
  USING (get_user_role() IN ('editor', 'admin', 'super_admin'))
  WITH CHECK (get_user_role() IN ('editor', 'admin', 'super_admin'));

CREATE POLICY "Editors/Admins/SuperAdmins can write projects" ON projects FOR ALL 
  USING (get_user_role() IN ('editor', 'admin', 'super_admin'))
  WITH CHECK (get_user_role() IN ('editor', 'admin', 'super_admin'));

CREATE POLICY "Editors/Admins/SuperAdmins can write team_members" ON team_members FOR ALL 
  USING (get_user_role() IN ('editor', 'admin', 'super_admin'))
  WITH CHECK (get_user_role() IN ('editor', 'admin', 'super_admin'));

CREATE POLICY "Editors/Admins/SuperAdmins can write testimonials" ON testimonials FOR ALL 
  USING (get_user_role() IN ('editor', 'admin', 'super_admin'))
  WITH CHECK (get_user_role() IN ('editor', 'admin', 'super_admin'));

CREATE POLICY "Editors/Admins/SuperAdmins can write blog_categories" ON blog_categories FOR ALL 
  USING (get_user_role() IN ('editor', 'admin', 'super_admin'))
  WITH CHECK (get_user_role() IN ('editor', 'admin', 'super_admin'));

CREATE POLICY "Editors/Admins/SuperAdmins can write blog_posts" ON blog_posts FOR ALL 
  USING (get_user_role() IN ('editor', 'admin', 'super_admin'))
  WITH CHECK (get_user_role() IN ('editor', 'admin', 'super_admin'));

CREATE POLICY "Editors/Admins/SuperAdmins can write careers" ON careers FOR ALL 
  USING (get_user_role() IN ('editor', 'admin', 'super_admin'))
  WITH CHECK (get_user_role() IN ('editor', 'admin', 'super_admin'));

CREATE POLICY "Editors/Admins/SuperAdmins can write equipment" ON equipment FOR ALL 
  USING (get_user_role() IN ('editor', 'admin', 'super_admin'))
  WITH CHECK (get_user_role() IN ('editor', 'admin', 'super_admin'));

CREATE POLICY "Editors/Admins/SuperAdmins can write faqs" ON faqs FOR ALL 
  USING (get_user_role() IN ('editor', 'admin', 'super_admin'))
  WITH CHECK (get_user_role() IN ('editor', 'admin', 'super_admin'));

-- Media Library
CREATE POLICY "Allow public read media" ON media_library FOR SELECT USING (true);
CREATE POLICY "Authenticated users can manage media records" ON media_library FOR ALL 
  USING (get_user_role() IN ('editor', 'admin', 'super_admin'));

-- Contact Messages & Quote Requests: Insertable by anyone (Public submissions), manageable by authorized users
CREATE POLICY "Public can submit contact messages" ON contact_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Authorized users can manage contact messages" ON contact_messages FOR ALL 
  USING (get_user_role() IN ('editor', 'admin', 'super_admin'));

CREATE POLICY "Public can submit quote requests" ON quote_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Authorized users can manage quote requests" ON quote_requests FOR ALL 
  USING (get_user_role() IN ('editor', 'admin', 'super_admin'));

-- Settings & SEO (Only Admin and Super Admin can manage)
CREATE POLICY "Admins/SuperAdmins can edit website settings" ON website_settings FOR ALL 
  USING (get_user_role() IN ('admin', 'super_admin'))
  WITH CHECK (get_user_role() IN ('admin', 'super_admin'));

CREATE POLICY "Admins/SuperAdmins can edit SEO metadata" ON seo_metadata FOR ALL 
  USING (get_user_role() IN ('admin', 'super_admin'))
  WITH CHECK (get_user_role() IN ('admin', 'super_admin'));
