-- ═══════════════════════════════════════════════════════════════════════════
-- MIGRATION V9: Recruitment Portal Tables & Policies
-- Run this in your Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- ═══════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 1: Add New Fields to careers Table
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.careers ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE public.careers ADD COLUMN IF NOT EXISTS salary TEXT;
ALTER TABLE public.careers ADD COLUMN IF NOT EXISTS vacancies INTEGER DEFAULT 1;
ALTER TABLE public.careers ADD COLUMN IF NOT EXISTS deadline TIMESTAMP WITH TIME ZONE;

-- Add UNIQUE constraint to slug if we want it to be unique
ALTER TABLE public.careers DROP CONSTRAINT IF EXISTS careers_slug_key;
ALTER TABLE public.careers ADD CONSTRAINT careers_slug_key UNIQUE (slug);

-- Populate existing null slugs based on the title
UPDATE public.careers 
SET slug = lower(regexp_replace(title, '[^a-zA-Z0-9]+', '-', 'g'))
WHERE slug IS NULL;


-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 2: Create job_applications Table
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.job_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  career_id BIGINT REFERENCES public.careers(id) ON DELETE CASCADE NOT NULL,
  
  -- Personal Information
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  nationality TEXT NOT NULL,
  city TEXT NOT NULL,
  
  -- Professional Information
  education_level TEXT NOT NULL,
  years_experience INTEGER NOT NULL,
  current_employer TEXT,
  current_position TEXT,
  expected_salary TEXT,
  start_date DATE,
  
  -- Questionnaire
  interest_reason TEXT NOT NULL,
  experience_summary TEXT NOT NULL,
  
  -- Document Upload URLs
  cv_url TEXT NOT NULL,
  cover_letter_url TEXT,
  certificates_url TEXT,
  portfolio_url TEXT,
  id_url TEXT,
  
  -- Status
  status TEXT DEFAULT 'New' NOT NULL, -- New, Under Review, Shortlisted, Interview Scheduled, Hired, Rejected
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 3: Enable RLS and Setup Policies
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.job_applications ENABLE ROW LEVEL SECURITY;

-- 1. Anyone can submit an application (Anonymous/Public INSERT)
DROP POLICY IF EXISTS "Allow public insert job_applications" ON public.job_applications;
CREATE POLICY "Allow public insert job_applications" 
  ON public.job_applications FOR INSERT 
  WITH CHECK (true);

-- 2. Only authorized users (editors, admins, super_admins) can view or modify applications
DROP POLICY IF EXISTS "Authorized users can manage applications" ON public.job_applications;
CREATE POLICY "Authorized users can manage applications" 
  ON public.job_applications FOR ALL 
  USING (public.get_user_role(auth.uid()) IN ('editor', 'admin', 'super_admin'))
  WITH CHECK (public.get_user_role(auth.uid()) IN ('editor', 'admin', 'super_admin'));
