-- MIGRATION V2: Extend services table with full SEO and content fields

ALTER TABLE services ADD COLUMN IF NOT EXISTS short_description TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS full_seo_description TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS hero_image_url TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS gallery_images JSONB DEFAULT '[]';
ALTER TABLE services ADD COLUMN IF NOT EXISTS key_features JSONB DEFAULT '[]';
ALTER TABLE services ADD COLUMN IF NOT EXISTS benefits JSONB DEFAULT '[]';
ALTER TABLE services ADD COLUMN IF NOT EXISTS work_process JSONB DEFAULT '[]';
ALTER TABLE services ADD COLUMN IF NOT EXISTS service_faqs JSONB DEFAULT '[]';
ALTER TABLE services ADD COLUMN IF NOT EXISTS related_projects JSONB DEFAULT '[]';
ALTER TABLE services ADD COLUMN IF NOT EXISTS related_blog_posts JSONB DEFAULT '[]';
ALTER TABLE services ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS meta_description TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS focus_keywords TEXT[];
ALTER TABLE services ADD COLUMN IF NOT EXISTS canonical_url TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS og_title TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS og_description TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS og_image TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS twitter_card TEXT DEFAULT 'summary_large_image';
ALTER TABLE services ADD COLUMN IF NOT EXISTS robots_meta TEXT DEFAULT 'index, follow';
ALTER TABLE services ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'published';
ALTER TABLE services ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0;

-- UPSERT 11 services

INSERT INTO services (title, slug, description, icon, image_url, tag, duration, value, scope, status, display_order, seo_title, meta_description, canonical_url, focus_keywords, og_title, og_description, og_image)
VALUES ('Commercial Construction', 'commercial-construction', 'Office towers, retail complexes, and mixed-use developments built to exacting standards.', 'Building2', 'https://images.unsplash.com/photo-1599707254554-027aeb4deacd?w=600&h=400&fit=crop&auto=format', 'Commercial', '6–18 Months', '$500K – $50M', 'Full Turnkey', 'published', 1, 'Commercial Construction Services | Office & Retail Builds', 'Expert commercial construction services specializing in office towers, retail complexes, and mixed-use developments. ISO 9001 certified with on-time delivery guarantees.', '/services/commercial-construction', ARRAY['commercial construction','office tower construction','retail complex builders'], 'Commercial Construction Services', 'Expert commercial construction services for office towers, retail complexes, and mixed-use developments.', 'https://images.unsplash.com/photo-1599707254554-027aeb4deacd?w=1200&h=630&fit=crop')
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title, description = EXCLUDED.description, icon = EXCLUDED.icon, image_url = EXCLUDED.image_url, tag = EXCLUDED.tag, duration = EXCLUDED.duration, value = EXCLUDED.value, scope = EXCLUDED.scope, display_order = EXCLUDED.display_order, seo_title = EXCLUDED.seo_title, meta_description = EXCLUDED.meta_description, canonical_url = EXCLUDED.canonical_url, focus_keywords = EXCLUDED.focus_keywords, og_title = EXCLUDED.og_title, og_description = EXCLUDED.og_description;

INSERT INTO services (title, slug, description, icon, image_url, tag, duration, value, scope, status, display_order, seo_title, meta_description, canonical_url, focus_keywords, og_title, og_description, og_image)
VALUES ('Industrial & Infrastructure', 'industrial-infrastructure', 'Warehouses, factories, bridges, and infrastructure projects delivered on schedule.', 'HardHat', 'https://images.unsplash.com/photo-1527335988388-b40ee248d80c?w=600&h=400&fit=crop&auto=format', 'Industrial', '12–36 Months', '$1M – $100M', 'Design-Build', 'published', 2, 'Industrial & Infrastructure Construction | Warehouses & Factories', 'Industrial construction and infrastructure projects including warehouses, factories, bridges, and heavy civil works. Delivered on schedule with precision engineering.', '/services/industrial-infrastructure', ARRAY['industrial construction','warehouse building','infrastructure contractor'], 'Industrial & Infrastructure Construction', 'Warehouses, factories, bridges, and infrastructure projects delivered on schedule.', 'https://images.unsplash.com/photo-1527335988388-b40ee248d80c?w=1200&h=630&fit=crop')
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title, description = EXCLUDED.description, icon = EXCLUDED.icon, image_url = EXCLUDED.image_url, tag = EXCLUDED.tag, duration = EXCLUDED.duration, value = EXCLUDED.value, scope = EXCLUDED.scope, display_order = EXCLUDED.display_order, seo_title = EXCLUDED.seo_title, meta_description = EXCLUDED.meta_description, canonical_url = EXCLUDED.canonical_url, focus_keywords = EXCLUDED.focus_keywords, og_title = EXCLUDED.og_title, og_description = EXCLUDED.og_description;

INSERT INTO services (title, slug, description, icon, image_url, tag, duration, value, scope, status, display_order, seo_title, meta_description, canonical_url, focus_keywords, og_title, og_description, og_image)
VALUES ('Residential Development', 'residential-development', 'Custom homes, apartment blocks, and estate communities crafted with precision.', 'Hammer', 'https://images.unsplash.com/photo-1644221150186-5d785a471f44?w=600&h=400&fit=crop&auto=format', 'Residential', '3–12 Months', '$100K – $5M', 'Custom Build', 'published', 3, 'Residential Construction | Custom Homes, Apartments & Estate Communities', 'Bespoke residential construction services for custom homes, apartment buildings, and estate developments. Quality craftsmanship, transparent pricing, and on-time delivery guaranteed.', '/services/residential-development', ARRAY['residential construction','custom home builder','apartment construction'], 'Residential Development', 'Custom homes, apartment blocks, and estate communities crafted with precision.', 'https://images.unsplash.com/photo-1644221150186-5d785a471f44?w=1200&h=630&fit=crop')
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title, description = EXCLUDED.description, icon = EXCLUDED.icon, image_url = EXCLUDED.image_url, tag = EXCLUDED.tag, duration = EXCLUDED.duration, value = EXCLUDED.value, scope = EXCLUDED.scope, display_order = EXCLUDED.display_order, seo_title = EXCLUDED.seo_title, meta_description = EXCLUDED.meta_description, canonical_url = EXCLUDED.canonical_url, focus_keywords = EXCLUDED.focus_keywords, og_title = EXCLUDED.og_title, og_description = EXCLUDED.og_description;

INSERT INTO services (title, slug, description, icon, image_url, tag, duration, value, scope, status, display_order, seo_title, meta_description, canonical_url, focus_keywords, og_title, og_description, og_image)
VALUES ('Renovation & Retrofit', 'renovation-retrofit', 'Structural upgrades, façade renovations, and full interior retrofits for existing buildings.', 'Wrench', 'https://images.unsplash.com/photo-1583024011792-b165975b52f5?w=600&h=400&fit=crop&auto=format', 'Renovation', '1–6 Months', '$50K – $2M', 'Partial / Full', 'published', 4, 'Renovation & Retrofit Services | Structural Upgrades & Façade Renovation', 'Expert building renovation and structural retrofit services for commercial and residential properties. From façade re-clads to seismic upgrades and complete interior overhauls.', '/services/renovation-retrofit', ARRAY['building renovation','structural retrofit','facade renovation'], 'Renovation & Retrofit Services', 'Structural upgrades, facade renovations, and full interior retrofits for existing buildings.', 'https://images.unsplash.com/photo-1583024011792-b165975b52f5?w=1200&h=630&fit=crop')
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title, description = EXCLUDED.description, icon = EXCLUDED.icon, image_url = EXCLUDED.image_url, tag = EXCLUDED.tag, duration = EXCLUDED.duration, value = EXCLUDED.value, scope = EXCLUDED.scope, display_order = EXCLUDED.display_order, seo_title = EXCLUDED.seo_title, meta_description = EXCLUDED.meta_description, canonical_url = EXCLUDED.canonical_url, focus_keywords = EXCLUDED.focus_keywords, og_title = EXCLUDED.og_title, og_description = EXCLUDED.og_description;

INSERT INTO services (title, slug, description, icon, image_url, tag, duration, value, scope, status, display_order, seo_title, meta_description, canonical_url, focus_keywords, og_title, og_description, og_image)
VALUES ('Architectural & Engineering', 'architectural-engineering', 'In-house architects, structural engineers, building plans, and design consultancy from concept to blueprint.', 'Ruler', 'https://images.unsplash.com/photo-1774600166818-e554a4d4c376?w=600&h=400&fit=crop&auto=format', 'Design', '2–8 Months', 'Custom Quote', 'Consultancy', 'published', 5, 'Architectural & Engineering Services | Building Plans, Design & Structural Engineering', 'Comprehensive architectural design, structural engineering, building plans, roof design, and design consultancy services. BIM-proficient, code-compliant, design-build ready.', '/services/architectural-engineering', ARRAY['architectural services','structural engineering','building plans','design consultation'], 'Architectural & Engineering Services', 'In-house architects and structural engineers providing concept-to-blueprint services including building plans, roof design, and design consultation.', 'https://images.unsplash.com/photo-1774600166818-e554a4d4c376?w=1200&h=630&fit=crop')
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title, description = EXCLUDED.description, icon = EXCLUDED.icon, image_url = EXCLUDED.image_url, tag = EXCLUDED.tag, duration = EXCLUDED.duration, value = EXCLUDED.value, scope = EXCLUDED.scope, display_order = EXCLUDED.display_order, seo_title = EXCLUDED.seo_title, meta_description = EXCLUDED.meta_description, canonical_url = EXCLUDED.canonical_url, focus_keywords = EXCLUDED.focus_keywords, og_title = EXCLUDED.og_title, og_description = EXCLUDED.og_description;

INSERT INTO services (title, slug, description, icon, image_url, tag, duration, value, scope, status, display_order, seo_title, meta_description, canonical_url, focus_keywords, og_title, og_description, og_image)
VALUES ('Civil & Earthworks', 'civil-earthworks', 'Site preparation, excavation, grading, drainage, cabro pavements, walkways, driveways, landscaping, and boundary walls.', 'Truck', 'https://images.unsplash.com/photo-1580901369227-308f6f40bdeb?w=600&h=400&fit=crop&auto=format', 'Civil', '1–12 Months', '$200K – $20M', 'Subcontract / Prime', 'published', 6, 'Civil & Earthworks | Site Preparation, Cabro Pavements, Landscaping & Drainage', 'Professional civil and earthworks services including site preparation, excavation, cabro pavements, walkways, driveways, landscaping, boundary walls, and drainage systems.', '/services/civil-earthworks', ARRAY['civil construction','earthworks contractor','cabro pavements','landscaping','drainage works'], 'Civil & Earthworks Services', 'Site preparation, earthworks, cabro pavements, landscaping, boundary walls, and drainage services.', 'https://images.unsplash.com/photo-1580901369227-308f6f40bdeb?w=1200&h=630&fit=crop')
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title, description = EXCLUDED.description, icon = EXCLUDED.icon, image_url = EXCLUDED.image_url, tag = EXCLUDED.tag, duration = EXCLUDED.duration, value = EXCLUDED.value, scope = EXCLUDED.scope, display_order = EXCLUDED.display_order, seo_title = EXCLUDED.seo_title, meta_description = EXCLUDED.meta_description, canonical_url = EXCLUDED.canonical_url, focus_keywords = EXCLUDED.focus_keywords, og_title = EXCLUDED.og_title, og_description = EXCLUDED.og_description;

INSERT INTO services (title, slug, description, icon, image_url, tag, duration, value, scope, status, display_order, seo_title, meta_description, canonical_url, focus_keywords, og_title, og_description, og_image)
VALUES ('Interior & Exterior Finishes', 'interior-exterior-finishes', 'Floor tiling, wall tiling, interior and exterior painting, waterproofing, and surface sealing for beautiful, lasting results.', 'Layers', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop&auto=format', 'Finishes', '2–8 Weeks', 'Custom Quote', 'Full / Partial', 'published', 7, 'Interior & Exterior Finishes | Tiling, Painting & Waterproofing Services', 'Professional interior and exterior finishing services including floor tiling, wall tiling, interior and exterior painting, and waterproofing. Quality craftsmanship with durable results.', '/services/interior-exterior-finishes', ARRAY['floor tiling','wall tiling','interior painting','exterior painting','waterproofing'], 'Interior & Exterior Finishes', 'Professional tiling, painting, and waterproofing services for residential and commercial buildings.', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=630&fit=crop')
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title, description = EXCLUDED.description, icon = EXCLUDED.icon, image_url = EXCLUDED.image_url, tag = EXCLUDED.tag, duration = EXCLUDED.duration, value = EXCLUDED.value, scope = EXCLUDED.scope, display_order = EXCLUDED.display_order, seo_title = EXCLUDED.seo_title, meta_description = EXCLUDED.meta_description, canonical_url = EXCLUDED.canonical_url, focus_keywords = EXCLUDED.focus_keywords, og_title = EXCLUDED.og_title, og_description = EXCLUDED.og_description;

INSERT INTO services (title, slug, description, icon, image_url, tag, duration, value, scope, status, display_order, seo_title, meta_description, canonical_url, focus_keywords, og_title, og_description, og_image)
VALUES ('Carpentry & Timber Works', 'carpentry-timber-works', 'Wooden door and window installation, timber framing, custom woodwork, and interior joinery crafted by skilled carpenters.', 'HardHat', 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&h=400&fit=crop&auto=format', 'Carpentry', '1–4 Weeks', 'Custom Quote', 'Supply & Install', 'published', 8, 'Carpentry & Timber Works | Wooden Doors, Windows, Framing & Custom Joinery', 'Expert carpentry and timber works including wooden window and door installation, timber framing, custom woodwork, and interior joinery. Precision craftsmanship using quality timber.', '/services/carpentry-timber-works', ARRAY['carpentry services','timber works','wooden door installation','timber framing','custom woodwork'], 'Carpentry & Timber Works', 'Expert wooden door and window installation, timber framing, and custom joinery services.', 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=1200&h=630&fit=crop')
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title, description = EXCLUDED.description, icon = EXCLUDED.icon, image_url = EXCLUDED.image_url, tag = EXCLUDED.tag, duration = EXCLUDED.duration, value = EXCLUDED.value, scope = EXCLUDED.scope, display_order = EXCLUDED.display_order, seo_title = EXCLUDED.seo_title, meta_description = EXCLUDED.meta_description, canonical_url = EXCLUDED.canonical_url, focus_keywords = EXCLUDED.focus_keywords, og_title = EXCLUDED.og_title, og_description = EXCLUDED.og_description;

INSERT INTO services (title, slug, description, icon, image_url, tag, duration, value, scope, status, display_order, seo_title, meta_description, canonical_url, focus_keywords, og_title, og_description, og_image)
VALUES ('Masonry & Building Materials', 'masonry-building-materials', 'Concrete block and clay brick production, stone dressing, masonry construction, and building stone supply.', 'Layers', 'https://images.unsplash.com/photo-1565372195458-9de0b320ef04?w=600&h=400&fit=crop&auto=format', 'Masonry', '1–6 Months', 'Custom Quote', 'Supply / Build', 'published', 9, 'Masonry & Building Materials | Concrete Blocks, Clay Bricks & Stone Works', 'Expert masonry construction and building materials supply including concrete block production, clay brick production, stone dressing, and masonry works. Durable, precision-crafted for lasting structures.', '/services/masonry-building-materials', ARRAY['masonry services','concrete block production','clay brick production','stone dressing'], 'Masonry & Building Materials', 'Concrete block production, clay bricks, stone dressing, and expert masonry construction services.', 'https://images.unsplash.com/photo-1565372195458-9de0b320ef04?w=1200&h=630&fit=crop')
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title, description = EXCLUDED.description, icon = EXCLUDED.icon, image_url = EXCLUDED.image_url, tag = EXCLUDED.tag, duration = EXCLUDED.duration, value = EXCLUDED.value, scope = EXCLUDED.scope, display_order = EXCLUDED.display_order, seo_title = EXCLUDED.seo_title, meta_description = EXCLUDED.meta_description, canonical_url = EXCLUDED.canonical_url, focus_keywords = EXCLUDED.focus_keywords, og_title = EXCLUDED.og_title, og_description = EXCLUDED.og_description;

INSERT INTO services (title, slug, description, icon, image_url, tag, duration, value, scope, status, display_order, seo_title, meta_description, canonical_url, focus_keywords, og_title, og_description, og_image)
VALUES ('Land Surveying', 'land-surveying', 'Site surveying, topographical surveys, boundary surveys, and construction setting out by qualified land surveyors.', 'Ruler', 'https://images.unsplash.com/photo-1582621404618-fc4b2e4dfc9d?w=600&h=400&fit=crop&auto=format', 'Surveying', '1–5 Days', 'Custom Quote', 'Consultancy', 'published', 10, 'Land Surveying Services | Site Survey, Topographical & Construction Setting Out', 'Professional land surveying services including site surveying, topographical surveys, boundary surveys, and construction setting out. Precision measurements for accurate planning and construction.', '/services/land-surveying', ARRAY['land surveying','site survey','topographical survey','boundary survey','construction setting out'], 'Land Surveying Services', 'Professional land surveying including site surveys, topographical mapping, boundary demarcation, and construction setting out.', 'https://images.unsplash.com/photo-1582621404618-fc4b2e4dfc9d?w=1200&h=630&fit=crop')
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title, description = EXCLUDED.description, icon = EXCLUDED.icon, image_url = EXCLUDED.image_url, tag = EXCLUDED.tag, duration = EXCLUDED.duration, value = EXCLUDED.value, scope = EXCLUDED.scope, display_order = EXCLUDED.display_order, seo_title = EXCLUDED.seo_title, meta_description = EXCLUDED.meta_description, canonical_url = EXCLUDED.canonical_url, focus_keywords = EXCLUDED.focus_keywords, og_title = EXCLUDED.og_title, og_description = EXCLUDED.og_description;

INSERT INTO services (title, slug, description, icon, image_url, tag, duration, value, scope, status, display_order, seo_title, meta_description, canonical_url, focus_keywords, og_title, og_description, og_image)
VALUES ('Construction Project Management', 'construction-project-management', 'Site supervision, material management, store keeping, scheduling, quality assurance, and full project coordination.', 'ClipboardList', 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&h=400&fit=crop&auto=format', 'Management', '1–36 Months', 'Custom Quote', 'Full Management', 'published', 11, 'Construction Project Management | Site Supervision, Scheduling & Quality Assurance', 'Professional construction project management services including site supervision, material management, store keeping, site record keeping, scheduling, quality assurance, and project coordination.', '/services/construction-project-management', ARRAY['construction project management','site supervision','material management','construction scheduling'], 'Construction Project Management', 'Expert site supervision, scheduling, quality assurance, and full project coordination for construction projects.', 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&h=630&fit=crop')
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title, description = EXCLUDED.description, icon = EXCLUDED.icon, image_url = EXCLUDED.image_url, tag = EXCLUDED.tag, duration = EXCLUDED.duration, value = EXCLUDED.value, scope = EXCLUDED.scope, display_order = EXCLUDED.display_order, seo_title = EXCLUDED.seo_title, meta_description = EXCLUDED.meta_description, canonical_url = EXCLUDED.canonical_url, focus_keywords = EXCLUDED.focus_keywords, og_title = EXCLUDED.og_title, og_description = EXCLUDED.og_description;
